### ISSUE TITLE
Как ее пройти?

### ISSUE THREAD

**Issue by ghost** [n1zamu/NCaptcha#1]
![image](https://github.com/user-attachments/assets/581ee0b4-7f59-4a4c-a3be-5f310c607f48)

**Comment by n1zamu** [comment]
Зависит от твоей версии сервера, капча работает только на 1.16.5

**Comment by ghost** [comment]
> Зависит от твоей версии сервера, капча работает только на 1.16.5

о как значит я дурак раз пытался запустить на 1.21 ,

**Comment by n1zamu** [comment]
Ну вообще хорошо бы было зарефакторить плагин и адаптировать его под все версии, возможно займусь этим :D
